proxy:
  listen:
    address: "127.0.0.1"
    port: 8080
  services:
    - name: my-service
      domain: my-service.my-company.com
      hosts:
        - address: "httpbin_1"
          port: 80
        - address: "httpbin_2"
          port: 80
    - name: echo-service
      domain: httpbin.org
      hosts:
        - address: "httpbin.org"
          port: 80
        - address: "httpbin_2"
          port: 80
