version: '3.9'
services:
  revox:
    build: .
    ports: 
      - 8080:8080
    volumes: 
      - "./config.yaml:/config.yaml"
        
  httpbin_1:
    image: kennethreitz/httpbin
    ports: 
      - 81:80    

  httpbin_2:
    image: kennethreitz/httpbin
    ports: 
      - 82:80