{{- if .Values.demo.enabled }}
{{ range $i, $e := until (int .Values.demo.instances) }}
{{ $i = add1 $i }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-{{$i}}
  labels:
    app.kubernetes.io/name: httpbin-{{$i}}
spec:
  {{- if not $.Values.demo.autoscaling.enabled }}
  replicas: {{ $.Values.demo.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: httpbin-{{$i}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpbin-{{$i}}
    spec:
      containers:
        - name: httpbin
          image: "{{ $.Values.demo.image.repository }}:{{ $.Values.demo.image.tag | default "latest" }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /get
              port: http
          readinessProbe:
            httpGet:
              path: /get
              port: http
          resources:
            {{- toYaml $.Values.demo.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-{{$i}}
  labels:
    app.kubernetes.io/name: httpbin-{{$i}}
spec:
  type: {{ $.Values.demo.service.type }}
  ports:
    - port: {{ $.Values.demo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: httpbin-{{$i}}
---
{{ end }}
{{- end }}