version: '3.9'
services:
  revox:
    build: .
    ports: 
      - 8080:8080
    volumes: 
      - "./config.json:/config.json"
        
  httpbin_1:
    image: kennethreitz/httpbin
    ports: 
      - 81:80    

  httpbin_2:
    image: kennethreitz/httpbin
    ports: 
      - 82:80
        
networks:
  revvv:
